/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package EditorTexto;

/**
 *
 * @author leos_
 */
public class EditorInterface2 extends javax.swing.JFrame {

    /**
     * Creates new form EditorInterface2
     */
    public EditorInterface2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textArea1 = new java.awt.TextArea();
        bttNegrito = new javax.swing.JButton();
        bttItalico = new javax.swing.JButton();
        bttSublinhado = new javax.swing.JButton();
        bttDesfazer = new javax.swing.JButton();
        bttRefazer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menubarArquivo = new javax.swing.JMenu();
        arquivobarAbrir = new javax.swing.JMenuItem();
        arquivobarNovo = new javax.swing.JMenuItem();
        arquivobarSalvar = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        menubarEditar = new javax.swing.JMenu();
        editarbarCopiar = new javax.swing.JMenuItem();
        editarbarColar = new javax.swing.JMenuItem();
        editarbarRecortar = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        editarbarDesfazer = new javax.swing.JMenuItem();
        editarbarRefazer = new javax.swing.JMenuItem();
        menubarUsuario = new javax.swing.JMenu();
        usuariobarTrocar = new javax.swing.JMenuItem();
        usuariobarSair = new javax.swing.JMenuItem();
        menubarSobre = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bttNegrito.setText("N");

        bttItalico.setText("I");
        bttItalico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttItalicoActionPerformed(evt);
            }
        });

        bttSublinhado.setText("S");

        bttDesfazer.setText("Desfa.");

        bttRefazer.setText("Refa.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bttNegrito)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttItalico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttSublinhado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttDesfazer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bttRefazer)
                .addGap(0, 542, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttNegrito)
                    .addComponent(bttItalico)
                    .addComponent(bttSublinhado)
                    .addComponent(bttDesfazer)
                    .addComponent(bttRefazer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        menubarArquivo.setText("Arquivo");

        arquivobarAbrir.setText("Abrir");
        menubarArquivo.add(arquivobarAbrir);

        arquivobarNovo.setText("Novo");
        arquivobarNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquivobarNovoActionPerformed(evt);
            }
        });
        menubarArquivo.add(arquivobarNovo);

        arquivobarSalvar.setText("Salvar");
        menubarArquivo.add(arquivobarSalvar);

        jMenuItem4.setText("jMenuItem4");
        menubarArquivo.add(jMenuItem4);

        jMenuBar1.add(menubarArquivo);

        menubarEditar.setText("Editar");

        editarbarCopiar.setText("Copiar");
        menubarEditar.add(editarbarCopiar);

        editarbarColar.setText("Colar");
        menubarEditar.add(editarbarColar);

        editarbarRecortar.setText("Recortar");
        editarbarRecortar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarbarRecortarActionPerformed(evt);
            }
        });
        menubarEditar.add(editarbarRecortar);
        menubarEditar.add(jSeparator1);

        editarbarDesfazer.setText("Desfazer");
        editarbarDesfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarbarDesfazerActionPerformed(evt);
            }
        });
        menubarEditar.add(editarbarDesfazer);

        editarbarRefazer.setText("Refazer");
        menubarEditar.add(editarbarRefazer);

        jMenuBar1.add(menubarEditar);

        menubarUsuario.setText("Usuario");

        usuariobarTrocar.setText("Trocar Usuario");
        menubarUsuario.add(usuariobarTrocar);

        usuariobarSair.setText("Sair do usuario");
        usuariobarSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuariobarSairActionPerformed(evt);
            }
        });
        menubarUsuario.add(usuariobarSair);

        jMenuBar1.add(menubarUsuario);

        menubarSobre.setText("Sobre");
        jMenuBar1.add(menubarSobre);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arquivobarNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquivobarNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arquivobarNovoActionPerformed

    private void editarbarRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarbarRecortarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarbarRecortarActionPerformed

    private void editarbarDesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarbarDesfazerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarbarDesfazerActionPerformed

    private void usuariobarSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuariobarSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuariobarSairActionPerformed

    private void bttItalicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttItalicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttItalicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorInterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorInterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorInterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorInterface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorInterface2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem arquivobarAbrir;
    private javax.swing.JMenuItem arquivobarNovo;
    private javax.swing.JMenuItem arquivobarSalvar;
    private javax.swing.JButton bttDesfazer;
    private javax.swing.JButton bttItalico;
    private javax.swing.JButton bttNegrito;
    private javax.swing.JButton bttRefazer;
    private javax.swing.JButton bttSublinhado;
    private javax.swing.JMenuItem editarbarColar;
    private javax.swing.JMenuItem editarbarCopiar;
    private javax.swing.JMenuItem editarbarDesfazer;
    private javax.swing.JMenuItem editarbarRecortar;
    private javax.swing.JMenuItem editarbarRefazer;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menubarArquivo;
    private javax.swing.JMenu menubarEditar;
    private javax.swing.JMenu menubarSobre;
    private javax.swing.JMenu menubarUsuario;
    private java.awt.TextArea textArea1;
    private javax.swing.JMenuItem usuariobarSair;
    private javax.swing.JMenuItem usuariobarTrocar;
    // End of variables declaration//GEN-END:variables
}
